backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/research/index.md"
        label: "Research"
        name: "research"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "research-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/publications/index.md"
        label: "Publications"
        name: "publications"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "publications-page"}
          - {label: Title, name: title, widget: string}
          - {label: Publications, name: publications, widget: object, fields: [
              {label: Authors, name: authors, widget: text},
              {label: Title, name: title, widget: text},
              {label: Journal, name: journal, widget: text},
              {label: Link, name: link, widget: text},
            ]}
      - file: "src/pages/cv/index.md"
        label: "Cv"
        name: "cv"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cv-page"}
          - {label: Title, name: title, widget: string}
          - {label: Education, name: education, widget: object, fields: [
              {label: What, name: what, widget: markdown},
              {label: Where, name: where, widget: string},
              {label: When, name: when, widget: string},
            ]}
          - {label: Research, name: research, widget: object, fields: [
              {label: What, name: what, widget: markdown},
              {label: Description, name: description, widget: markdown},
              {label: Where, name: where, widget: string},
              {label: When, name: when, widget: string},
            ]}
          - {label: Awards, name: awards, widget: object, fields: [
              {label: What, name: what, widget: markdown},
              {label: Description, name: description, widget: markdown},
              {label: When, name: when, widget: string},
            ]}
          - {label: Presentations, name: presentations, widget: object, fields: [
              {label: What, name: what, widget: markdown},
              {label: Where, name: where, widget: string},
              {label: When, name: when, widget: string},
            ]}
